steps:
  # INSTALL / CONFIGURE ########################################################
  - id: '🔑 Refresh Artifact Registry access token'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    # name: node:${_NODE_VERSION}
    entrypoint: npx
    args: ['google-artifactregistry-auth', '--repo-config=.npmrc']
  - id: '⚙️ Install dependencies'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['ci']
  # AUDIT ######################################################################
  - id: '🛡️ Audit dependencies'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['audit', '--audit-level=moderate']
  # BUILD ######################################################################
  - id: '🔧 Build libraries'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['run', 'build:libs']
  # - id: '🔧 Build scripts'
  #   name: 'docker.io/library/node:${_NODE_VERSION}'
  #   entrypoint: npm
  #   args: ['run', 'build:scripts']
  # - id: '🔧 Build application audit'
  #   name: 'docker.io/library/node:${_NODE_VERSION}'
  #   entrypoint: npm
  #   args: ['run', 'build', '-w packages/audit']
  # TEST #######################################################################
  - id: '🔍 Test library checks'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['run', 'test:ci', '-w packages/checks']
  - id: '🔍 Test library hapi-healthcheck-plugin'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['run', 'test:ci', '-w packages/hapi-healthcheck-plugin']
  - id: '🔍 Test library hapi-ip-whitelist-plugin'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['run', 'test:ci', '-w packages/hapi-ip-whitelist-plugin']
  # - id: '🔍 Test library utils'
  #   name: 'docker.io/library/node:${_NODE_VERSION}'
  #   entrypoint: npm
  #   args: ['run', 'test:ci', '-w packages/utils']
  # RELEASE ####################################################################
  - id: 'Copy dotfiles'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    args: ['./scripts/copy-dotfiles.mjs', '--package utils']
  - id: '🚀 Release to Artifact Registry with multi-semantic-release'
    name: 'docker.io/library/node:${_NODE_VERSION}'
    entrypoint: npm
    args: ['run', 'release']
    # The github token must allow to push to this GitHub repository.
    secretEnv: ['GITHUB_TOKEN']
    # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SA_ARTIFACT_REGISTRY_WRITER }}

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/GITHUB_TOKEN/versions/${_GITHUB_TOKEN_VERSION}
    env: 'GITHUB_TOKEN'

# user-defined substitutions and default values
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions
substitutions:
  _GITHUB_TOKEN_VERSION: 'latest'
  _NODE_VERSION: 17.9.0
options:
  dynamic_substitutions: true