steps:
  - id: '🐋 Build container image'
    name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '.'
      - '--file=Dockerfile'
      - '--build-arg=APP_NAME=${_CLOUD_RUN_SERVICE_ID}'
      - '--tag=${_CONTAINER_IMAGE}'

  # - id: '👀 List container images'
  #   name: gcr.io/cloud-builders/docker
  #   args: ['image', 'ls']

  - id: '🛫 Push container image to Artifact Registry'
    name: gcr.io/cloud-builders/docker
    args: ['push', "${_CONTAINER_IMAGE}"]

  - id: '🚀 Deploy application as a Cloud Run service'
    name: gcr.io/cloud-builders/gcloud:${_GCLOUD_VERSION}
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_CLOUD_RUN_SERVICE_ID} \
          --allow-unauthenticated \
          --image ${_CONTAINER_IMAGE} \
          --memory ${_MEMORY} \
          --min-instances 0 \
          --max-instances 2 \
          --platform managed \
          --project ${PROJECT_ID} \
          --region ${_CLOUD_RUN_REGION} \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-env-vars NODE_ENV=production \
          --set-secrets APP_CONFIG=${_APP_CONFIG_SECRET_NAME}:${_APP_CONFIG_SECRET_VERSION} \
          --set-secrets TELEGRAM=${_TELEGRAM_SECRET_NAME}:${_TELEGRAM_SECRET_VERSION} \
          --timeout ${_CLOUD_RUN_SERVICE_REQUEST_TIMEOUT} \
          --update-labels customer=${_CUSTOMER},resource=cloud_run_service \
          --verbosity warning

# user-defined substitutions and default values
substitutions:
  _APP_CONFIG_SECRET_NAME: WEBHOOKS_CONFIG_PRODUCTION
  _APP_CONFIG_SECRET_VERSION: latest
  _ARTIFACT_REGISTRY_DOCKER_REPOSITORY_ID: cloud-run-source-deploy
  _ARTIFACT_REGISTRY_DOCKER_REPOSITORY_LOCATION_ID: europe-west3
  _CLOUD_RUN_SERVICE_ID: ${_CONTAINER_IMAGE_NAME}
  _CLOUD_RUN_REGION: europe-west3
  # https://cloud.google.com/run/docs/configuring/request-timeout
  _CLOUD_RUN_SERVICE_REQUEST_TIMEOUT: 10s
  _CONTAINER_IMAGE: "${_ARTIFACT_REGISTRY_DOCKER_REPOSITORY_LOCATION_ID}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_DOCKER_REPOSITORY_ID}/${_CONTAINER_IMAGE_NAME}:${_CONTAINER_IMAGE_TAG}"
  _CONTAINER_IMAGE_NAME: calderone-webhooks
  _CONTAINER_IMAGE_TAG: latest
  _CUSTOMER: personal
  _GCLOUD_VERSION: latest
  # M = megabyte, Mi = mebibyte, G = gigabyte, Gi = gibibyte
  # https://cloud.google.com/run/docs/configuring/memory-limits
  _MEMORY: 256M
  _SERVICE_ACCOUNT: sa-webhooks@prj-kitchen-sink.iam.gserviceaccount.com
  _TELEGRAM_SECRET_NAME: TELEGRAM
  _TELEGRAM_SECRET_VERSION: latest

options:
    # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
    dynamic_substitutions: true
