steps:
  - id: Refresh Artifact Registry access token
    name: 'docker.io/library/node:${_NODE_VERSION}'
    # name: node:${_NODE_VERSION}
    entrypoint: npx
    args: ['google-artifactregistry-auth', '--repo-config=.npmrc']
  - id: 'Install dependencies'
    name: node:${_NODE_VERSION}
    entrypoint: npm
    args: ['install']
  - id: Audit dependencies
    name: node:${_NODE_VERSION}
    entrypoint: npm
    args: ['audit', '--audit-level=moderate']
  - id: Build
    name: node:${_NODE_VERSION}
    entrypoint: npm
    args: ['run', 'build:ci']
  - id: Test
    name: node:${_NODE_VERSION}
    entrypoint: npm
    args: ['run', 'test:ci']

# user-defined substitutions and default values
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions
substitutions:
  _NODE_VERSION: 16.15.0
options:
  dynamic_substitutions: true