defaultService: https://www.googleapis.com/compute/beta/projects/prj-kitchen-sink/global/backendServices/backend-webhooks
hostRules:
- hosts:
  - audit.giacomodebidda.com
  pathMatcher: path-matcher-1
- hosts:
  - webhooks.giacomodebidda.com
  pathMatcher: path-matcher-2
kind: compute#urlMap
name: url-map-giacomodebidda-com
pathMatchers:
- defaultService: https://www.googleapis.com/compute/beta/projects/prj-kitchen-sink/global/backendServices/backend-audit
  name: path-matcher-1
- defaultService: https://www.googleapis.com/compute/beta/projects/prj-kitchen-sink/global/backendServices/backend-webhooks
  name: path-matcher-2
selfLink: https://www.googleapis.com/compute/beta/projects/prj-kitchen-sink/global/urlMaps/url-map-giacomodebidda-com