#!/bin/bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

# Upload all coverage reports to Codecov #######################################
# https://docs.codecov.io/docs/about-the-codecov-bash-uploader#arguments
# This command displays the help and exits
# bash <(curl -s https://codecov.io/bash) -h
################################################################################

packages_root="$PWD/packages"

for package_full_path in "$packages_root"/*
  do
    package_name=$(basename "$package_full_path")
    if [ -d "$package_full_path/coverage" ]
      then
        # coverage_dir="$package_full_path/coverage/lcov-report"
        coverage_file="$package_full_path/coverage/lcov.info"
        flag=$package_name
        name=$package_name
        # echo "upload coverage report of package \"$package_name\" to Codecov. Coverage dir: $coverage_dir"
        # bash <(curl -s https://codecov.io/bash) -c -s $coverage_dir -F $flag -n $name -t $CODECOV_TOKEN
        echo "upload coverage report of package \"$package_name\" to Codecov. Coverage file: $coverage_file"
        bash <(curl -s https://codecov.io/bash) -c -f $coverage_file -F $flag -n $name -t $CODECOV_TOKEN
      else
        echo "No coverage report found for $package_name"
      fi
  done
