steps:
  - id: '⚙️ Install Node.js dependencies'
    name: node:${_NODE_VERSION}
    entrypoint: npm
    args: ['install']

  # - id: '👀 Check filesystem'
  #   name: gcr.io/cloud-builders/gcloud:latest
  #   entrypoint: /bin/bash
  #   args:
  #     - -c
  #     - ls -1ah

  - id: '🚀 Deploy to Cloud Functions (2nd generation)'
    name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud beta functions deploy ${_FUNCTION_NAME} \
          --gen2 \
          --runtime nodejs18 \
          --source ./ \
          --allow-unauthenticated \
          --entry-point ${_FUNCTION_ENTRY_POINT} \
          --memory ${_MEMORY} \
          --min-instances 0 \
          --max-instances 3 \
          --project ${PROJECT_ID} \
          --region ${_CLOUD_FUNCTIONS_REGION} \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-env-vars ${_DEBUG} \
          --set-env-vars FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION} \
          --set-env-vars NODE_ENV=production \
          --set-secrets TELEGRAM_BOT=${_TELEGRAM_BOT_SECRET_NAME}:latest \
          --timeout ${_REQUEST_TIMEOUT} \
          --trigger-http \
          --update-labels customer=${_CUSTOMER},resource=function \
          --verbosity info

# user-defined substitutions and default values
substitutions:
  _CLOUD_FUNCTIONS_REGION: europe-west3
  _CUSTOMER: personal
  # log a few namespaces to understand how Telegraf works.
  # Since there is a comma in the string, I define ## as the custom delimiter
  _DEBUG: "^##^DEBUG=telegraf:main,telegraf:webhook"
  _FIRESTORE_COLLECTION: workflows_callbacks
  _FUNCTION_ENTRY_POINT: telegramBot
  _FUNCTION_NAME: telegram-bot
  # M = megabyte, Mi = mebibyte, G = gigabyte, Gi = gibibyte
  # https://cloud.google.com/functions/docs/configuring/memory
  _MEMORY: 128Mi
  _NODE_VERSION: 18.12.1
  _REQUEST_TIMEOUT: 30s
  _SERVICE_ACCOUNT: sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  _TELEGRAM_BOT_SECRET_NAME: TELEGRAM_BOT

options:
  # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
  dynamic_substitutions: true
