export enum Emoji {
  Bomb = '💣',
  Customer = '👤',
  Document = '📄',
  Error = '🚨',
  Failure = '❌',
  Finished = '🏁',
  Fix = '🔧',
  Inspect = '🔍',
  Invalid = '❌',
  Ledger = '📒',
  Link = '🔗',
  MailboxWithRaisedFlag = '📬',
  Memo = '📝',
  Notification = '💬',
  Ok = '✅',
  Scroll = '📜',
  Sparkles = '✨',
  Started = '🎬',
  Stop = '🛑',
  Success = '✅',
  Timer = '⏱️',
  User = '👤',
  Warning = '⚠️'
}
