auditConfigs:
- auditLogConfigs:
  - logType: ADMIN_READ
  - logType: DATA_WRITE
  - logType: DATA_READ
  service: workflowexecutions.googleapis.com
bindings:
- members:
  - group:developers@giacomodebidda.com
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  - serviceAccount:sa-github-workflows@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/artifactregistry.reader
- members:
  - serviceAccount:sa-artifact-registry-writer@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/artifactregistry.writer
- members:
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/bigquery.dataEditor
- members:
  - serviceAccount:vantage-6a919e899c93451913a9@vantage-production-308619.iam.gserviceaccount.com
  role: roles/bigquery.jobUser
- members:
  - serviceAccount:service-1051247446620@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com
  role: roles/bigquerydatatransfer.serviceAgent
- members:
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  - serviceAccount:sa-dash-earthquakes@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudbuild.builds.builder
- members:
  - serviceAccount:sa-github-workflows@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudbuild.builds.editor
- members:
  - serviceAccount:service-1051247446620@gcp-sa-cloudbuild.iam.gserviceaccount.com
  role: roles/cloudbuild.serviceAgent
- members:
  - serviceAccount:sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-webhooks@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/clouddebugger.agent
- members:
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  role: roles/cloudfunctions.developer
- members:
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudfunctions.invoker
- members:
  - serviceAccount:service-1051247446620@gcf-admin-robot.iam.gserviceaccount.com
  role: roles/cloudfunctions.serviceAgent
- members:
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudscheduler.admin
- members:
  - serviceAccount:service-1051247446620@gcp-sa-cloudscheduler.iam.gserviceaccount.com
  role: roles/cloudscheduler.serviceAgent
- members:
  - group:developers@giacomodebidda.com
  role: roles/cloudtasks.admin
- members:
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudtasks.enqueuer
- members:
  - serviceAccount:service-1051247446620@gcp-sa-cloudtasks.iam.gserviceaccount.com
  role: roles/cloudtasks.serviceAgent
- members:
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/cloudtasks.viewer
- members:
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/compute.instanceAdmin
- members:
  - serviceAccount:service-1051247446620@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-1051247446620@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-1051247446620@containerregistry.iam.gserviceaccount.com
  role: roles/containerregistry.ServiceAgent
- members:
  - serviceAccount:service-1051247446620@dataflow-service-producer-prod.iam.gserviceaccount.com
  role: roles/dataflow.serviceAgent
- members:
  - serviceAccount:sa-dataflow-worker@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/dataflow.worker
- members:
  - serviceAccount:service-1051247446620@gcp-sa-datapipelines.iam.gserviceaccount.com
  role: roles/datapipelines.serviceAgent
- members:
  - serviceAccount:sa-firestore-user-test@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/datastore.user
- members:
  - serviceAccount:sa-firestore-viewer-test@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/datastore.viewer
- members:
  - serviceAccount:1051247446620@cloudservices.gserviceaccount.com
  role: roles/editor
- members:
  - serviceAccount:sa-matsuri-demo-app@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-webhooks@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/errorreporting.writer
- members:
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/eventarc.eventReceiver
- members:
  - serviceAccount:service-1051247446620@gcp-sa-eventarc.iam.gserviceaccount.com
  role: roles/eventarc.serviceAgent
- members:
  - serviceAccount:firebase-service-account@firebase-sa-management.iam.gserviceaccount.com
  - serviceAccount:service-1051247446620@gcp-sa-firebase.iam.gserviceaccount.com
  role: roles/firebase.managementServiceAgent
- members:
  - serviceAccount:firebase-adminsdk-gzpeu@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/firebase.sdkAdminServiceAgent
- members:
  - serviceAccount:service-1051247446620@gcp-sa-firestore.iam.gserviceaccount.com
  role: roles/firestore.serviceAgent
- members:
  - group:developers@giacomodebidda.com
  - serviceAccount:firebase-adminsdk-gzpeu@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-artifact-registry-writer@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:service-1051247446620@gcp-sa-pubsub.iam.gserviceaccount.com
  role: roles/iam.serviceAccountTokenCreator
- members:
  - group:developers@giacomodebidda.com
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/iam.serviceAccountUser
- members:
  - serviceAccount:sa-dash-earthquakes@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-matsuri-demo-app@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/logging.logWriter
- members:
  - serviceAccount:sa-monitoring@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/monitoring.viewer
- members:
  - user:giacomo@giacomodebidda.com
  role: roles/owner
- members:
  - serviceAccount:sa-pubsub@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/pubsub.editor
- members:
  - serviceAccount:service-1051247446620@gcp-sa-pubsub.iam.gserviceaccount.com
  role: roles/pubsub.serviceAgent
- members:
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  role: roles/run.admin
- members:
  - serviceAccount:sa-dash-earthquakes@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/run.invoker
- members:
  - serviceAccount:service-1051247446620@serverless-robot-prod.iam.gserviceaccount.com
  role: roles/run.serviceAgent
- members:
  - serviceAccount:sa-secret-manager-admin-test@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/secretmanager.admin
- members:
  - serviceAccount:1051247446620@cloudbuild.gserviceaccount.com
  - serviceAccount:sa-matsuri-demo-app@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-notifier@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-webhooks@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
- members:
  - group:developers@giacomodebidda.com
  - serviceAccount:sa-github-workflows@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/storage.admin
- members:
  - serviceAccount:sa-storage-uploader@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
- members:
  - serviceAccount:sa-compute-engine@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/storage.objectViewer
- members:
  - serviceAccount:sa-dash-earthquakes@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/viewer
- members:
  - serviceAccount:sa-telegram-bot@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-wasm-news@prj-kitchen-sink.iam.gserviceaccount.com
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/workflows.invoker
- members:
  - serviceAccount:service-1051247446620@gcp-sa-workflows.iam.gserviceaccount.com
  role: roles/workflows.serviceAgent
- members:
  - serviceAccount:sa-workflows-runner@prj-kitchen-sink.iam.gserviceaccount.com
  role: roles/workflows.viewer
etag: BwX2UqMX7ko=
version: 1