#!/bin/sh

# Husky seems to run all hook scripts using sh, regardless of the shebang present
# in the git hook.
# https://github.com/typicode/husky/issues/971
. "$(dirname "$0")/_/husky.sh"

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eu

echo "PRE PUSH HOOK [destination remote: $1] [location remote: $2]"

echo "run commitlint"
npx commitlint --config ./config/commitlint.cjs --to HEAD
